version: '3'
services:
  redis:
    image: 'redis:latest'
    networks:
      - fooclient-network
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './:/var/www/html:delegated'
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated'
      - './.docker/ssl:/etc/ssl:delegated'
    depends_on:
      - phpfpm
    networks:
      - fooclient-network
  phpfpm:
    image: 'junaidbhura/wp-php-fpm-dev:8.0'
    environment:
      XDEBUG_MODE: 'off'
    volumes:
      - './:/var/www/html:delegated'
      - './.docker/php-fpm/wp-cli.yml:/var/www/html/wp-cli.yml:delegated'
      - './.docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini:delegated'
    user: '33:33'
    depends_on:
      - redis
      - database
    networks:
      - fooclient-network
  database:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - fooclient-network
    volumes:
      - 'db_data:/var/lib/mysql'
      - './.docker/mysql/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '3306:3306'
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - fooclient-network
networks:
  fooclient-network:
    driver: bridge
volumes:
  db_data:
