name: Coding Standards and Tests

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

env:
  DB_NAME: wp_tests
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: mysql
  WP_HOME: http://localhost:8889
  WP_SITEURL: http://localhost:8889/wp

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: junaidbhura/wp-tests:php-7.4
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Composer cache
      id: composer-cache
      uses: actions/cache@v1
      with:
        path: vendor
        key: composer-${{ hashFiles( 'composer.lock' ) }}

    - name: NodeJS cache
      id: node-cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-${{ hashFiles( 'package-lock.json' ) }}

    - name: WP cache
      id: wp-cache
      uses: actions/cache@v1
      with:
        path: web/wp
        key: wp-${{ hashFiles( 'composer.lock' ) }}

    - name: WP plugins cache
      id: wp-plugins-cache
      uses: actions/cache@v1
      with:
        path: web/wp-content/plugins
        key: wp-plugins-${{ hashFiles( 'composer.lock' ) }}

    - name: Install Composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install

    - name: Install NodeJS dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: PHP Coding standards
      run: npm run lint:php

    - name: JS Coding standards
      run: npm run lint:js

    - name: CSS Coding standards
      run: npm run lint:css

    - name: Create database
      run: mysqladmin create $DB_NAME --user=$DB_USER --password=$DB_PASSWORD --host=$DB_HOST --protocol=tcp

    - name: PHPUnit Tests
      run: npm run test:php

    - name: E2E Tests
      run: |
        wp core install --url="http://localhost:8889" --title="E2E Tests" --admin_user=admin --admin_password=password --admin_email=info@example.com --allow-root
        cd web
        php -S localhost:8889 > /dev/null 2>&1 &
        cd ..
        npm run build
        npm run test:e2e -- --wordpress-base-url=http://localhost:8889/wp
