name: Coding Standards and Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: php:7.2-apache
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        volumes:
          - $HOME/mysql:/var/lib/mysql

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git subversion default-mysql-client
        docker-php-ext-install -j$(nproc) pdo pdo_mysql mysqli mbstring

    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install Composer dependencies
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer
        composer global require "phpunit/phpunit=6.1.0"
        composer global require wp-coding-standards/wpcs
        $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

    - name: Install NodeJS dependencies
      run: npm install

    - name: Install WordPress test suite
      run: |
        bash ./.bin/install-wp-tests.sh wordpress_test root root mysql latest

    - name: PHP Coding standards
      run: composer run lint-php

    - name: JS Coding standards
      run: npm run lint-js

    - name: CSS Coding standards
      run: npm run lint-css

    - name: Unit tests
      run: composer run test
